[versions]
project-name = "XiaomiHelper"
android-compileSdk = "36"
android-minSdk = "35"
android-targetSdk = "36"
project-app-packageName = "dev.lackluster.mihelper"
project-app-versionName = "3.2.5"
project-app-versionCode = "325"

androidGradlePlugin = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.4"
xposed = "82"
yukihookapi = "1.3.1"
kavaref-core = "1.0.2"
kavaref-extension = "1.0.2"
dexkit = "2.0.7"
serialization-json = "1.10.0"

[libraries]
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }
yukihookapi-api = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukihookapi" }
yukihookapi-ksp-xposed = { group = "com.highcapable.yukihookapi", name = "ksp-xposed", version.ref = "yukihookapi" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavaref-core" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension", version.ref = "kavaref-extension" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version = "1.1.1" }

dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }

androidx-ui = { group = "androidx.compose.ui", name = "ui", version = "1.10.2" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }

androidx-test-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }